name: run_cmake_and_make

inputs:
  cmake_extra_vars:
    description: extra vars for cmake
    type: string
  make_command:
    description: make command
    type: string
  coveralls:
    description: on or off
    type: string

runs:
  using: "composite"
  steps:
    - name: install the required tools
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install cmake libboost-all-dev python2 curl libcurl4-openssl-dev cppcheck
    - name: run make
      shell: bash
      run: |
        rm locales/leatherman.pot && \
        cmake ${{ inputs.cmake_extra_vars }} . && \
        mkdir -p /tmp/leatherman/dest && \
        make ${{ inputs.make_command }} DESTDIR=/tmp/leatherman/dest -j2 && \
        { [[ '${{ inputs.coveralls }}' == 'ON' ]] && coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
