sudo: required
services:
  - docker

before_install:
  - docker pull gcr.io/cpp-projects/cpp-ci:1

script:
  - >
    docker run -v `pwd`:/leatherman gcr.io/cpp-projects/cpp-ci:1 /bin/bash -c "
    cd /leatherman &&
    rm locales/leatherman.pot &&
    cmake $EXTRA_VARS . &&
    mkdir dest &&
    make $TARGET DESTDIR=/leatherman/dest -j2 &&
    { [ '$COVERALLS' == 'ON' ] && coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
    "
  - if [ "$DO_RELEASE" == "true" ]; then tar czvf leatherman${PKG_SUFFIX}.tar.gz `find dest -type f -print`; fi

env:
  matrix:
    - TARGET=cpplint
    - TARGET=cppcheck
    - TARGET="all test install ARGS=-v" DO_RELEASE=true PKG_SUFFIX="" EXTRA_VARS="-DBOOST_STATIC=ON"
    - TARGET="all test install ARGS=-v" DO_RELEASE=true PKG_SUFFIX="-dynamic" EXTRA_VARS="-DLEATHERMAN_SHARED=ON"
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON" COVERALLS=ON
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DLEATHERMAN_USE_LOCALES=OFF"
    - TARGET="all test install ARGS=-v" EXTRA_VARS="-DLEATHERMAN_GETTEXT=OFF"

deploy:
  provider: releases
  api_key:
    secure: Hz0wjDyko1lu/0OwBBGK3cR4B7Io9ure+skv+m1aVCUlYibKTrFvwPJJmGD/S92xwe+DqD7r09K4h0Du9MxIyew3sgxVPdM54sRweKq4vuvgmw018vzqyU+EEvCPQiXCYQ/UrQ/0IRiCxysA5b9zbW8G9/Qy2du7sXWgNklMx1w5K0u/GZD9+vzzq7BrrH2bAaSF7g+1fjsODH3ABqqNwLbUZ0E1cvn+In5rOEfWmsGGshCXaTB+zINOsGC0hSnoY/s/YTTWiELi88UasCpJQrd++1qMO447qIKRDo4OltfxCvHOytwvzBmDU30NM5iIXZEqfGYTKcSF84xGu6dde6D1YKAMBnTW8a65rWstC297pcP+NuowFUxBV5iu97joO7cHcYdzsz42vPhboehW9x8juf333ftNC21pfhoh8iXNT3/xtG4rwfjY3iX/UcLZiEh2O0Gnhjqc3rqO5HqqzytDfuDe1NXN+jhBXz44HvrRE4SGo74yUYVuRx4advIe2AZZdExVRfphP8E/ZUAmOLmbRGWM398lggStPruoheCmzPElb3ubiS74eYSBKYgjxVjkHB2FGzvjj0W19NgcXh6568ptiF60t4T9odI2vYZTAG5Gsj6d0LP1KvEHAiO89tiza/yI+QKb+xfr+dVDJer4gK9YBMKTimUUTstl3oI=
  file_glob: true
  file: leatherman*.tar.gz
  skip_cleanup: true
  on:
    repo: puppetlabs/leatherman
    tags: true
    condition: '"$DO_RELEASE" == "true"'
