name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci_checks:
    strategy:
      fail-fast: false
      matrix:
        options:
          - make_command: cpplint
            cmake_extra_vars: -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2
          - make_command: cppcheck
          - make_command: all test install ARGS=-v
            cmake_extra_vars: -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON -DENABLE_CXX_WERROR=OFF
            coveralls: ON
          - make_command: all test install ARGS=-v
            cmake_extra_vars: -DLEATHERMAN_USE_LOCALES=OFF -DENABLE_CXX_WERROR=OFF
          - make_command: all test install ARGS=-v
            cmake_extra_vars: -DLEATHERMAN_GETTEXT=OFF -DENABLE_CXX_WERROR=OFF
    runs-on: ubuntu-latest
    steps:
      - name: checkout current pr
        uses: actions/checkout@v4
      - name: run CMake and Make
        uses: ./.github/actions/run_cmake_and_make
        with:
          cmake_extra_vars: ${{ matrix.options.cmake_extra_vars }}
          make_command: ${{ matrix.options.make_command }}
          coveralls: ${{ matrix.options.coveralls }}
